version: '3'
services:
  deno:
    image: deno-p
    volumes:
      - ./recast:/root/recast
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: "exit 0"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: euro21st@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 3JuqwDk9bMAG
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
  rest:
    image: postgrest/postgrest
    ports:
      - 8082:3000
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_OPENAPI_SERER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: api_user
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-store:
  pgadmin:
